name: flutter_frontend
description: "Chat Tho-Fi Flutter Web Application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  socket_io_client: ^2.0.3+1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  audioplayers: ^6.0.0
  universal_html: ^2.2.4
  emoji_picker_flutter: ^3.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "web/icon_1024.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
