workflows:
  flutter-ios:
    name: Flutter iOS Build
    working_directory: mobile_app
    instance_type: mac_mini_m1 # Gói cấu hình máy Mac mini M1 tiêu chuẩn
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS App (Chế độ Debug không cần chứng chỉ Apple để kiểm thử nhanh)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
