name: mobile_app
description: A brand new Flutter chat application connecting to a Node.js socket backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Thư viện WebView để nhúng trang web cũ vào app
  webview_flutter: ^4.4.2

  # Firebase & Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.1

  # Chat Bubble
  dash_bubble: ^2.0.0

  # Thư viện phục vụ Chat Native
  socket_io_client: ^2.0.3+1
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
