# Cấu hình Podfile chuẩn của Flutter tích hợp bản vá sửa lỗi Firebase iOS build

platform :ios, '12.0'

# Đường dẫn nạp các hàm cài đặt pod của Flutter
flutter_root = File.expand_path(File.join('..', '..', '..'), File.dirname(__FILE__))
if File.exist?(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))
  require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
elsif ENV['FLUTTER_ROOT']
  require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), ENV['FLUTTER_ROOT'])
else
  raise "Không tìm thấy thư mục cài đặt SDK Flutter. Vui lòng kiểm tra biến môi trường FLUTTER_ROOT."
end

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # FIX iOS: Sửa lỗi "Include of non-modular header inside framework module" của Firebase
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
